apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: branch-db
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: "root123"
  MARIADB_DATABASE: "branchdb"
  MARIADB_USER: "branchuser"
  MARIADB_PASSWORD: "maria123"